name: entify
version: 0.2.4
author: Peter Siroki <psiroki@skawa.hu>
description: A toolkit to ease the use of the datastore with the googleapis package.
homepage: https://github.com/skawa-universe/entify

dependencies:
  googleapis: ">=0.39.0 <0.50.0"

dev_dependencies:
  test:
